Added safe_sleep() and use it instead of time.sleep() in unit tests.
time.sleep() may sleep less than the requested time if a signal is caught,
and this might cause test failures like this (from debian i386 buildd):

=================================== FAILURES ===================================
____________________________ fs_api_tests.test_read ____________________________
Traceback (most recent call last):
  File "/«BUILDDIR»/s3ql-2.10.1+dfsg/tests/t3_fs_api.py", line 246, in test_read
    self.assertGreater(inode_after.atime, inode_before.atime)
  File "/usr/lib/python3.4/unittest/case.py", line 1188, in assertGreater
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.4/unittest/case.py", line 642, in fail
    raise self.failureException(msg)
AssertionError: 1407493110.242212 not greater than 1407493110.242212
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
============== 1 failed, 480 passed, 1 warnings in 166.13 seconds ==============